# Generated by Django 4.2 on 2023-04-12 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='xit',
            field=models.CharField(default=django.utils.timezone.now, max_length=244),
            preserve_default=False,
        ),
    ]
